name: liveview_flutter
description: "Phoenix LiveViewNative Flutter client"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  html: ^0.15.4
  web_socket_channel: ^2.3.0
  uuid: ^4.4.2
  phoenix_socket: ^0.7.4
  xml: ^6.5.0
  provider: ^6.1.2
  flutter_form_builder: "9.4.1"
  json_annotation: ^4.9.0
  json_theme:
    git:
      url: https://github.com/aalloul/json_theme.git
      path: json_theme
  shared_preferences: ^2.3.1
  golden_toolkit: ^0.15.0
  event_hub: ^0.2.1
  html_unescape: ^2.0.0
  throttled: ^1.0.1
  cached_network_image: ^3.4.1
  http_query_string: ^1.0.0
  universal_html: ^2.2.4
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
